version: "2"
linters:
  default: none
  enable:
    - errcheck
    - copyloopvar
    - dupl
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - gocyclo
    - testifylint
    - bodyclose
    - whitespace
    - thelper
    - cyclop
    - gocognit
    - funlen
    - gomodguard
    - contextcheck
    - errorlint
    - nilerr
  settings:
    errcheck:
      check-type-assertions: true
    funlen:
      lines: 90
      statements: 40
    cyclop:
      max-complexity: 15
      package-average: 10.0
    testifylint:
      enable-all: true
      disable:
        - require-error
    goconst:
      min-len: 2
      min-occurrences: 2
    revive:
      rules:
        - name: exported
          arguments: [disableChecksOnVariables, disableChecksOnConstants]
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
      enabled-tags:
        - performance
        - style
        - experimental
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - dupl
          - gosec
          - funlen
          - gocognit
          - cyclop
          - errcheck
        path: _test\.go
      - linters:
          - revive
          - unused
        path: _test\.go$
        text: unused-parameter
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
